os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip
jobs:
  include:
    - name: failing
      script: true
after_succes:
  - echo done
  - echo $TRAVIS_TEST_RESULT
  - echo $MY_SECRET_VAR
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
env:
  global:
    secure: $MY_SECRET_VAR
